# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftGitHubClient' do
  use_frameworks!

  target 'RxSwiftGitHubClientTests' do
    inherit! :search_paths
  end

end
